**Das numpy Modul importieren, um es verwenden zu können:**

In [1]:
import numpy as np

**Wir können nun Arrays erstellen und mit zufälligen Werten füllen.**

**Ein Tensor ist eindimensional, also besitzt es eine shap mit einem Wert: shape=(_size_)**

**Eine Matrix ist zweidimensional, also besitzt sie eine shape mit zwei Werten: shape=(_zeilen_, _spalten_)**

**Um nun ein Array zu erstellen, kann folgender Befehl genutzt werden:**

**np.random.uniform(_min_, _max_, _shape_)**


In [2]:
#Zwei Vektoren mit 3 Werten
vector1 = np.random.uniform(-0.5,0.5,(3)) # Werte zwischen -0.5 und 0.5
vector2 = np.random.uniform(-1,1, (3)) # Werte zwischen -1 und 1

#Eine Matrix mit drei Zeilen und zwei Spalten
matrice = np.random.uniform(-0.5,0.5, (3,2)) # Werte zwischen -0.5 und 0.5


#Arrays ausgeben
print("vector1:")
print(vector1)
print("\nvensor2:")
print(vector2)
print("\nmatrice:")
print(matrice)

vector1:
[-0.05931032 -0.23089223 -0.10698298]

vensor2:
[-0.52171645  0.11428961 -0.36030022]

matrice:
[[ 0.02623612  0.47228666]
 [ 0.34014683 -0.24994308]
 [ 0.01546724  0.34990901]]


**Addieren und Subtrahieren von Tensoren**

In [15]:
print("vector1 und vector2 addiert:")
print(vector1 + vector2)

print("\nvector2 von vector1 subtrahiert:")
print(vector1 - vector2)

vector1 und vector2 addiert:
[ 1.00637794  0.54300209 -0.88588018]

vector2 von vector1 subtrahiert:
[-2.63170295e-01 -5.30783304e-01  4.16322745e-04]


**Hadamard-Produkt zweier Tensoren bilden**

**Mathematische Schreibweise: tensor1 ⊗ tensor2**

In [16]:
print("Hadamard Produkt von vector1 und vector2:")
print(vector1 * vector2)

Hadamard Produkt von vector1 und vector2:
[0.23588449 0.00328009 0.19619588]


**Matrixmultiplikation**

**Mathematische Schreibweise: tensor1 * tensor2**

In [17]:
print("Matrixprodukt von matrice und vector1")
print(vector1@matrice)

Matrixprodukt von matrice und vector1
[-0.02004958 -0.0444881 ]


**Eine Matrix transponieren (Zeile und Spalte vertauschen)**
**Mathematische Schreibweise: matrice^T

In [4]:
print(matrice.T)

[[-0.19211982 -0.13582062  0.06605181]
 [ 0.05142288  0.12236384  0.08554814]]


Werte der Matrix einer Achse aufsummieren:

In [3]:
print("Auf Zeilenebene:")
print(matrice.sum(axis=0))

print("\n Auf Spaltenebene:")
print(matrice.sum(axis=1))

Auf Zeilenebene:
[0.38185019 0.57225259]

 Auf Spaltenebene:
[0.49852278 0.09020375 0.36537625]
